merged

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,26 +1,25 @@
 #!/bin/sh
 
 OSTYPE=$(uname)
-if [ -z "$OSTYPE" ]
-then
-    echo "OSTYPE is empty"
-    exit 1
+if [ -z "$OSTYPE" ]; then
+	echo "OSTYPE is empty"
+	exit 1
 fi
 
 case $OSTYPE in
-    "linux-gnu"*|"darwin"*|"cygwin"|"msys"|"FreeBSD")
-        _SYSTEM=unix
-    
-        ;;
-    "win32")
-        _SYSTEM=windows
+"linux-gnu"* | "darwin"* | "cygwin" | "msys" | "FreeBSD")
+	_SYSTEM=unix
 
-        ;;
-    *)
-        echo "ERROR - $OSTYPE"
-        exit 1
+	;;
+"win32")
+	_SYSTEM=windows
 
-        ;;
+	;;
+*)
+	echo "ERROR - $OSTYPE"
+	exit 1
+
+	;;
 esac
 
 cp $_SYSTEM/home/.git-hooks ~/
